### ISSUE TITLE
Herzien van de commit van 6 maart 2024

### ISSUE THREAD

**Issue by bdeclerc** [11ways/audit-introteksten#1]
De aanpassingen aan de introteksten uitgevoerd op 6 maart zijn niet doorsproken geweest tussen de controle-entiteiten maar komen er op initiatief van alleen de Vlaamse overheid - aangezien momenteel deze teksten "universeel" zijn moeten we dit terugrollen, ik hoop met de entiteiten tot een consensus te komen (ik laat voorlopig in het midden of die consensus ook een aanpassing van de tekst zal vergen)

**Comment by cstrobbe** [comment]
Gelieve te preciseren om welke van de vijf commits van 6 maart het hier gaat.

**Comment by bdeclerc** [comment]
Sorry, gaat om de wijzigingen aan "bosa-intros.html"

**Comment by cstrobbe** [comment]
De [recentste commit](https://github.com/11ways/audit-introteksten/commit/4d8f214b37e10229f28b194b8683f31cc2d99188) verwijdert de tekst "is gedeeltelijk toegankelijk, aangezien ze / hij slechts gedeeltelijk voldoet aan de toegankelijkheidsvereisten in" en herstelt de originele versie.
De toevoeging " / app" (inclusief vertalingen) staat er nog in; ik neem aan dat hiermee geen probleem is.

**Comment by bdeclerc** [comment]
Nee, daar heb ik idd geen probleem mee. Bedankt! Ik neem het nog verder op met zowel de Vlaamse overheid als intern bij ons om af te stemmen voor de toekomst.

**Comment by cstrobbe** [comment]
@bdeclerc Zijn de teksten in `bosa-intros.html` nu in orde, zodat dit issue gesloten kan worden?
